name: Publish Package to Github NPM Registry

on:
    release:
        types: [published]

jobs:
    test-and-publish:
        name: Test and Publishsh
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup NodeJS Version -20x
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://npm.pkg.github.com'

            - name: Install Dependencies
              run: npm install

            - name: Publish to GitHub NPM Registry
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
